Repository chasubeen/TalesRunnner, pull requests merged in 2025-02, with the labels that each got.

#5 annotation 전처리 코드
  [Euron7th]_annotation.ipynb
Labels: data

#7 Caption 전처리 코드
  data/Image_Captioning_BLIP.ipynb
  data/Merged_Dataset.ipynb
Labels: data

#10 koT5 training
  koT5_finetuning.ipynb
Labels: story generator

#11 Inference(streamlit demo)
  streamlit/app.py
  streamlit/streamlit.ipynb
Labels: pipeline
